//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoyolabCookie.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoyolabCookie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;mhy-article-card-wrapper&quot;&gt;
        ///    &lt;div class=&quot;mhy-article-card&quot;&gt;
        ///        &lt;div class=&quot;mhy-article-card__header&quot;&gt;
        ///            &lt;div class=&quot;mhy-article-card__userinfo&quot;&gt;
        ///                &lt;div class=&quot;mhy-user-card mhy-article-card__user mhy-user-card-md&quot; style=&quot;cursor: auto;&quot;&gt;
        ///                    &lt;div class=&quot;mhy-avatar mhy-user-card__avatar mhy-avatar__l3&quot;&gt;
        ///                        &lt;img class=&quot;mhy-avatar__img&quot; src=&quot;https://img-os-static.hoyolab.com/favicon.ico&quot; lazy=&quot;loaded&quot;&gt;
        ///                    &lt;/d[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string article_list {
            get {
                return ResourceManager.GetString("article_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function changePage() {
        ///    let content = document.querySelector(&apos;.root-page-container__content&apos;);
        ///    content.removeChild(document.querySelector(&apos;.root-page-container__right&apos;));
        ///    document.querySelector(&apos;.root-page-container&apos;).style.minWidth = &apos;0&apos;;
        ///    let header = document.querySelector(&quot;.mhy-page-header-content &gt; #mhy-switch-tab &gt; ul&quot;);
        ///    for (let ele of header.children) ele.remove();
        ///    header.querySelector(&apos;.mhy-switch-tab__label &gt; span&apos;).textContent = i18n.get(&apos;cookie&apos;);
        ///    let article_li[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string changePage {
            get {
                return ResourceManager.GetString("changePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon hoyolab {
            get {
                object obj = ResourceManager.GetObject("hoyolab", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;lang&gt;
        ///	&lt;en-US&gt;
        ///		&lt;cookie&gt;Cookie&lt;/cookie&gt;
        ///		&lt;cookie_ready&gt;Cookies are ready&lt;/cookie_ready&gt;
        ///		&lt;cookie_copy&gt;Copy Cookies&lt;/cookie_copy&gt;
        ///		&lt;copied&gt;Copied.&lt;/copied&gt;
        ///	&lt;/en-US&gt;
        ///	&lt;ko-KR&gt;
        ///		&lt;cookie&gt;쿠키&lt;/cookie&gt;
        ///		&lt;cookie_ready&gt;쿠키 준비완료&lt;/cookie_ready&gt;
        ///		&lt;cookie_copy&gt;쿠키 복사&lt;/cookie_copy&gt;
        ///		&lt;copied&gt;복사되었습니다.&lt;/copied&gt;
        ///	&lt;/ko-KR&gt;
        ///&lt;/lang&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string i18n {
            get {
                return ResourceManager.GetString("i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var userLang = navigator.language || navigator.userLanguage; 
        ///i18n.init(userLang);과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string i18n_initialize {
            get {
                return ResourceManager.GetString("i18n_initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _loginCT = setInterval(() =&gt; {
        ///    if (!location.href.includes(&quot;hoyolab&quot;)) {
        ///        clearInterval(_loginCT);
        ///        return
        ///    }
        ///    let e = document.querySelector(&quot;.login-box-side_bottom__btn&quot;);
        ///    e &amp;&amp; !document.querySelector(&quot;#hyv-account-sdk-frame&quot;) &amp;&amp; (e.click(), clearInterval(_loginCT), window.changePage());
        ///}, 100);과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loaded_login {
            get {
                return ResourceManager.GetString("loaded_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _loginCT = setInterval(() =&gt; {
        ///    let e = document.querySelector(&apos;div[aria-label=&quot;dialog&quot;]&apos;);
        ///    let l = document.querySelector(&apos;button[aria-label=&quot;close&quot;]&apos;);
        ///    if (e) {
        ///        e.removeChild(l);
        ///        let a = document.createElement(&apos;style&apos;);
        ///        a.textContent = &apos;div[aria-label=&quot;dialog&quot;] {border-radius: 0px !important;}&apos;;
        ///        document.body.appendChild(a);
        ///        document.querySelector(&apos;.el-overlay-dialog&apos;).style.overflow = &apos;hidden&apos;;
        ///        clearInterval(_loginCT);
        ///    }
        ///}, 100);과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string login_remove_close {
            get {
                return ResourceManager.GetString("login_remove_close", resourceCulture);
            }
        }
    }
}
